### ISSUE TITLE
label (@n) for taxonomy

### ISSUE THREAD

**Issue by charlymo** [wibarab/featuredb#11]
Added n="sedentismType" to taxonomy. Look for better term under which bedouin (=nomadic?), sedentary, mixed can be grouped.

**Comment by dasch124** [comment]
What would you call the dimension to be described by the taxonomy? "mobility"? So how about something along the lines of `mobilityGrade` ?  as a quick first idea ...

**Comment by charlymo** [comment]
Agreed on tradLingCat (=traditionLinguisticCategory), they are only used to reflect views in literature, not our research results.
I did a global replace already.
