### ISSUE TITLE
validation errors q-file "chapter"

### ISSUE THREAD

**Issue by VeronikaEngler** [wibarab/featuredb#26]
In the "chapter" of the q-file are two recurring errors that come up in validation:
<graphic type="symbol"></graphic> Das Attribut 'type' des Elements '{http://www.tei-c.org/ns/1.0}graphic' ist im DTD/Schema nicht definiert .      
<num type="instances"></num> Das Attribut 'type' des Elements '{http://www.tei-c.org/ns/1.0}num' ist im DTD/Schema nicht definiert .

**Comment by VeronikaEngler** [comment]
Oh and a third error:
<graphic type="symbol"></graphic> Erforderliches Attribut 'url' fehlt.

**Comment by dasch124** [comment]
In the 2023-03-30 meeting we agreeed to … 

* merge the two lists 
* remove `<graphic>` (as this will be left to the frontend)
* remove `<num>` (as this will change over time and needs to be calculated anyway)

**Comment by iriartedia89** [comment]
All done +:

-  divGen element 
- separating label from desc 
- pointers to labels
