### ISSUE TITLE
Commit number ce0cd788aaddfe7a15c8dc091da96f4e42eb261f - New locations in the Galilee by Ana (August 8th)

### ISSUE THREAD

**Issue by iriartedia89** [wibarab/featuredb#3]
Commit ce0cd788aaddfe7a15c8dc091da96f4e42eb261f (New locations in the Galilee by Ana - August 8th) was pushed but does not appear on TEI enricher. The modified files though are present in the backup folder. Since many other modifications have been done after that, how shall I proceed?

**Comment by dasch124** [comment]
It looks like your entries were deleted by accident by hand with the commit a224ebef8a8eda65

I took H̱ajajra as an example to trace what happend: 

Having a look at the git graph in visual studio you see that both you and @MariaRebecca were working on the geodata list:

![grafik](https://user-images.githubusercontent.com/4641281/184415504-ad83e145-7683-417b-8196-71b649d0f0fc.png)

* you added the "H̱ajajra" example with ce0cd788
![grafik](https://user-images.githubusercontent.com/4641281/184415842-acc5c190-3e3f-477b-a308-f9c4b652a244.png)

* in the meantime rebecca created commit 2e5ffdb9c715c7 - obviously the H̱ajajra entry wasn't there yet
* then, Rebecca merged both of your changes into commit be2d1609 - this worked, the H̱ajajra entry was inserted in the merged document
![grafik](https://user-images.githubusercontent.com/4641281/184416266-3fa6b51a-bc91-4f72-987b-1feeb34dabe2.png)

* in the next commit (a224ebef8a) lots of lines where changed (17 added, 80 deleted) 
![grafik](https://user-images.githubusercontent.com/4641281/184416615-fd985ba0-dbfd-43e5-bb2a-1c7478df0569.png)

... with the H̱ajajra entry being one of them:

![grafik](https://user-images.githubusercontent.com/4641281/184416831-74a9be1b-044c-4dba-b1f4-ba5f36c30c79.png)

Here's the link to the line in the same commit on github https://github.com/wibarab/featuredb/commit/a224ebef8a8eda653959d20934bcd48ea3e1130c#diff-a2d87e1c32f49d36443426192203b3b6ca4c14caebff1a3b1c8b1beb84c748f4L1078

I would propose that you go through the changes made in a224ebef8a and check which one was by accident and which one was on purpose so you can copy-paste the entries deleted from a224ebef8a in the current version of the geodata list. Given that we don't know which deletions in a224ebef8a where done on accident and which ones on purpose, you'll have to do that by hand, unfortunately.

**Comment by iriartedia89** [comment]
This issue has been solved by reviewing and redoing the changes manually.
