### ISSUE TITLE
Authorship attribution for feature descriptions.

### ISSUE THREAD

**Issue by dasch124** [wibarab/featuredb#35]
As discussed in our meeting on 2023-12-21, we want to attribute authorship to the descriptive part of a feature document, potentially also for external contributors. For this, we should … 

* add `<byline>` to the ODD and make it mandatory within `<div type="description">` 
* add a  <listPerson xml:id="contributors"> to 010_manannot/wibarab_dmp.xml where the `<person>` elements for external contributors can be listed
* make `@resp` mandatory on `<div type="description">` 

Further, we should decide whether the author of the feature description should also be mentioned in the `<titleStmt>` (IMHO s*he should), and how (`<author>` ? `<respStmt>` with a dedicated `<resp>` ?)

**Comment by dasch124** [comment]
meeting 2024-01-11: we want to drop `<author>` in `<titleStmt>`

**Comment by kisram** [comment]
@dasch124 I added a constraintSpec like this, does that look right? (Seems to be doing what it should)
<elementSpec ident="div" mode="change">
    <constraintSpec ident="div-description" scheme="schematron">
        <constraint>
            <sch:ns prefix="tei" uri="http://www.tei-c.org/ns/1.0"/>
            <sch:rule context="tei:div[@type = 'description']">
                <sch:assert test="child::tei:byline"> 'byline' element is required.</sch:assert>
                <sch:assert test="@resp">'resp' attribute is required.</sch:assert>
            </sch:rule>
        </constraint>
    </constraintSpec>
    <attList>
        <attDef ident="type" mode="replace" usage="opt">
            <valList type="closed">
                <valItem ident="description"/>
                <valItem ident="featureDescription"/>
                <valItem ident="featureValueObservations"/>
            </valList>
        </attDef>
    </attList>
</elementSpec>

**Comment by dasch124** [comment]
Danke!
