### ISSUE TITLE
validation: make sure that fvo ids are globally unique 

### ISSUE THREAD

**Issue by dasch124** [wibarab/featuredb#37]
Theoretically, all fvo elements should have a globally unique xml:id by prefixing them with the document ids. Since this is beyond the current document-internal validation we've implemented so far, we need to add this. 

Currently there are some fvo ids where the "document id" part of the fvo id reads "tf_template". https://github.com/search?q=repo%3Awibarab%2Ffeaturedb+xml%3Aid%3D%22ft_template&type=code

**Comment by VeronikaEngler** [comment]
Yes, I fixed this. So unless I overlooked something somewhere all IDs should be globally unique.
