### ISSUE TITLE
Introduce controlled vocabulary for names of religions

### ISSUE THREAD

**Issue by dasch124** [wibarab/featuredb#5]
# Introduce controlled vocabulary for names of religions

feature value observations which are attested to a specific religious group contain a `<personGrp>` element: 

```xml
<personGrp type="religousGroup">
      <name>Christians</name>
</personGrp>
```
  
We want to limit the possible values of `<name>` to one of the following:

* Christians
* Jews
* Muslim
* Ibadi
* Malikite
* Sunni
* Shiite
* Druze

## TODO

- [ ] add to ODD (@dasch124 )
- [ ] introduce to tei_enricher (@charlymo) - related to https://gitlab.oeaw.ac.at/acdh-ch/object-pascal/tei-enricher/-/issues/4

**Comment by charlymo** [comment]
All above options added to snippets_wibarab_001.xml.
