### ISSUE TITLE
wrong relative paths pointing from feature document to profiles

### ISSUE THREAD

**Issue by dasch124** [wibarab/featuredb#8]
E.g. in 010_manannot/features/features_djim.xml:

```xml
    <wib:featureValueObservation cert="unknown" status="draft" xml:id="fr_0000_new_moon_please" resp="dmp:???">
         ...
               <ptr target="profiles\vicav_profile_LBN-ABI.xml"/>
          ...
    </wib>
```

Since the profiles are located under 010_manannot/profiles the `@target` attribute on `<ptr>` should read `..\profiles\vicav_profile_LBN-ABI.xml` Changing this in the data isn't a problem, but would this break something in the tei_enricher, @charlymo ?

**Comment by charlymo** [comment]
Resolved and replaced by lang
